/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-08 20:08:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<header class=\"header-area header-sticky text-center header-default\">\r\n");
      out.write("  <div class=\"header-main-sticky\">\r\n");
      out.write("    <div class=\"header-nav\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"nav-left float-left\"><div class=\"ttheader-service\">Wants to explore Upcoming Deals on Weekends?</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-right float-right d-flex\">\r\n");
      out.write("          <div class=\"ttheader-mail\"><a href=\"mailto:otakusrilanka@gmail.com\">otakusrilanka@gmail.com</a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"header-main-head\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"header-main\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"header-left float-left d-flex d-lg-flex d-md-block d-xs-block\">\r\n");
      out.write("            <div class=\"language-wrapper toggle\">\r\n");
      out.write("              <button type=\"button\" class=\"btn text-capitalize dropdown-toggle\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/img/banner/en.png\" alt=\"en\" height=\"12\" width=\"18\"/><span>English</span></button>\r\n");
      out.write("              <div id=\"language-dropdown\" class=\"language\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                  <li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/img/banner/en.png\" alt=\"en\" width=\"18\" height=\"12\"/><span>English</span></li>\r\n");
      out.write("                  <li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/img/banner/fr.png\" alt=\"fr\" width=\"18\" height=\"12\"/><span>French</span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"currency-wrapper toggle\">\r\n");
      out.write("              <button type=\"button\" class=\"btn text-capitalize dropdown-toggle\"><span>LKR</span></button>\r\n");
      out.write("              <div id=\"currency-dropdown\" class=\"currency\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                  <li><span>Euro</span></li>\r\n");
      out.write("                  <li><span>Pound Sterling</span></li>\r\n");
      out.write("                  <li><span>US Dollar</span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contact\">\r\n");
      out.write("              <i class=\"material-icons\">phone</i>\r\n");
      out.write("              <a href=\"tel:+94703889596\">0703889596</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"header-middle float-lg-left float-md-left float-sm-left float-xs-none\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("              <a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/img/logos/text-logo.png\" alt=\"logo\" width=\"200\" height=\"50\" ></a>		</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"header-right d-flex d-xs-flex d-sm-flex justify-content-end float-right\">\r\n");
      out.write("            <div class=\"search-wrapper\">\r\n");
      out.write("              <a>\r\n");
      out.write("                <i class=\"material-icons search\">search</i>\r\n");
      out.write("                <i class=\"material-icons close\">close</i>			</a>\r\n");
      out.write("              <form autocomplete=\"off\" action=\"/action_page.php\" class=\"search-form\">\r\n");
      out.write("                <div class=\"autocomplete\">\r\n");
      out.write("                  <input id=\"myInput\" type=\"text\" name=\"myCountry\" placeholder=\"Search here\">\r\n");
      out.write("                  <button type=\"button\"><i class=\"material-icons\">search</i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"user-info\">\r\n");
      out.write("              <button type=\"button\" class=\"btn\">\r\n");
      out.write("                <i class=\"material-icons\">perm_identity</i>		</button>\r\n");
      out.write("              <div id=\"user-dropdown\" class=\"user-menu\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                  <li><a href=\"my-account.html\" class=\"text-capitalize\">my account</a></li>\r\n");
      out.write("                  <li><a href=\"#\" class=\"modal-view button\" data-toggle=\"modal\" data-target=\"#modalRegisterForm\">Register</a></li>\r\n");
      out.write("                  <li><a href=\"#\" class=\"modal-view button\" data-toggle=\"modal\" data-target=\"#modalLoginForm\">login</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"cart-wrapper\">\r\n");
      out.write("              <button type=\"button\" class=\"btn\">\r\n");
      out.write("                <i class=\"material-icons\">shopping_cart</i>\r\n");
      out.write("                <span class=\"ttcount\">2</span>			</button>\r\n");
      out.write("              <div id=\"cart-dropdown\" class=\"cart-menu\">\r\n");
      out.write("                <ul class=\"w-100 float-left\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <table class=\"table table-striped\">\r\n");
      out.write("                      <tbody>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td class=\"text-center\"><a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/img/productDTO/01.jpg\" alt=\"01\" title=\"01\" height=\"104\" width=\"80\"></a></td>\r\n");
      out.write("                        <td class=\"text-left product-name\"><a href=\"#\">aliquam quaerat voluptatem</a>\r\n");
      out.write("                          <div class=\"quantity float-left w-100\">\r\n");
      out.write("                            <span class=\"cart-qty\">1 Ã </span>\r\n");
      out.write("                            <span class=\"text-left price\"> $20.00</span>						    </div>                          </td>\r\n");
      out.write("                        <td class=\"text-center close\"><a class=\"close-cart\"><i class=\"material-icons\">close</i></a></td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <table class=\"table price mb-30\">\r\n");
      out.write("                      <tbody>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td class=\"text-left\"><strong>Total</strong></td>\r\n");
      out.write("                        <td class=\"text-right\"><strong>$2,122.00</strong></td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"buttons w-100 float-left\">\r\n");
      out.write("                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart\">\r\n");
      out.write("                      <input class=\"btn pull-left mt_10 btn-primary btn-rounded w-100\" value=\"View cart\" type=\"submit\" onclick=\"viewCart()\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <form action=\"checkout_page.html\">\r\n");
      out.write("                      <input class=\"btn pull-right mt_10 btn-primary btn-rounded w-100\" value=\"Checkout\" type=\"submit\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"menu\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <!-- Navbar -->\r\n");
      out.write("          <nav class=\"navbar navbar-expand-lg navbar-light d-sm-none d-xs-none d-lg-block navbar-full\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Navbar brand -->\r\n");
      out.write("            <a class=\"navbar-brand text-uppercase d-none\" href=\"#\">Navbar</a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Collapse button -->\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent2\"\r\n");
      out.write("                    aria-controls=\"navbarSupportedContent2\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("              <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("            <!-- Collapsible content -->\r\n");
      out.write("            <div class=\"collapse navbar-collapse\">\r\n");
      out.write("\r\n");
      out.write("              <!-- Links -->\r\n");
      out.write("              <ul class=\"navbar-nav m-auto justify-content-center\">\r\n");
      out.write("                <li class=\"nav-item dropdown active\">\r\n");
      out.write("                  <a class=\"nav-link text-uppercase\" href=\"#\">\r\n");
      out.write("                    Home\r\n");
      out.write("                    <span class=\"sr-only\">(current)</span>        </a>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle text-uppercase\" href=\"#\">\r\n");
      out.write("                    Shop by Seires\r\n");
      out.write("                    <span class=\"sr-only\">(current)</span>        </a>\r\n");
      out.write("                  <div class=\"dropdown-menu mega-menu v-2 z-depth-1 special-color py-3 px-3\">\r\n");
      out.write("                    <div class=\"sub-menu mb-xl-0 mb-4\">\r\n");
      out.write("                      <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"index.html\">\r\n");
      out.write("                            Attack on Titan                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"index2.html\">\r\n");
      out.write("                            Death Note                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"index3.html\">\r\n");
      out.write("                            Jujutsu Kaisen                 </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"index4.html\">\r\n");
      out.write("                            Naruto                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"index5.html\">\r\n");
      out.write("                            One Piece                  </a>                </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown mega-dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle text-uppercase\" href=\"category.html\">Category</a>\r\n");
      out.write("                  <div class=\"dropdown-menu mega-menu v-2 z-depth-1 special-color py-3 px-3\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-md-12 col-xl-4 sub-menu mb-xl-0 mb-4\">\r\n");
      out.write("                        <h6 class=\"sub-title text-uppercase font-weight-bold white-text\">Variation 1</h6>\r\n");
      out.write("                        <!--Featured image-->\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("filter-toggle.html\">\r\n");
      out.write("                              filter toggle                  </a>                </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"off-canvas-left.html\">\r\n");
      out.write("                              off canvas left                </a>                </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"off-canvas-right.html\">\r\n");
      out.write("                              off canvas right                </a>                </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-6 col-xl-4 sub-menu mb-md-0 mb-4\">\r\n");
      out.write("                        <h6 class=\"sub-title text-uppercase font-weight-bold white-text\">Variation 2</h6>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"category-5-col.html\">\r\n");
      out.write("                              5 columns mode                 </a>                </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"category-6-col.html\">\r\n");
      out.write("                              6 columns mode                     </a>                </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"category-7-col.html\">\r\n");
      out.write("                              7 columns mode                     </a>                </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"category-8-col.html\">\r\n");
      out.write("                              8 columns mode                 </a>                </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-6 col-xl-4 sub-menu mb-0\">\r\n");
      out.write("\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <span class=\"menu-banner\"><img src=\"img/banner/menu-banner.jpg\" alt=\"menu-banner\" width=\"161\" height=\"230\"/></span>                </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link text-uppercase\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("shop\">\r\n");
      out.write("                    Shop\r\n");
      out.write("                    <span class=\"sr-only\">(current)</span>        </a>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle text-uppercase\" href=\"category.html\">Blog</a>\r\n");
      out.write("                  <div class=\"dropdown-menu mega-menu v-2 z-depth-1 special-color py-3 px-3\">\r\n");
      out.write("                    <div class=\"sub-menu\">\r\n");
      out.write("                      <h6 class=\"sub-title text-uppercase font-weight-bold white-text d-none\">Featured</h6>\r\n");
      out.write("                      <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"blog-2-column.html\">\r\n");
      out.write("                            blog 2 column                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"blog-3-column.html\">\r\n");
      out.write("                            blog 3 column                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"blog-2-column-masonary.html\">\r\n");
      out.write("                            blog masonary                 </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"blog-list.html\">\r\n");
      out.write("                            blog list                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"blog-details.html\">\r\n");
      out.write("                            blog details                  </a>                </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle text-uppercase\" href=\"category.html\">Pages</a>\r\n");
      out.write("                  <div class=\"dropdown-menu mega-menu v-2 z-depth-1 special-color py-3 px-3\">\r\n");
      out.write("                    <div class=\"sub-menu\">\r\n");
      out.write("                      <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"about-us.html\">\r\n");
      out.write("                            About us                 </a>				 </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"accordions.html\">\r\n");
      out.write("                            Accordions                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"buttons.html\">\r\n");
      out.write("                            Buttons              </a>                </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link text-uppercase\" href=\"contact-us.html\">contact us</a>      </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <!-- Links -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Collapsible content -->\r\n");
      out.write("\r\n");
      out.write("          </nav>\r\n");
      out.write("          <!-- Navbar -->\r\n");
      out.write("          <nav class=\"navbar navbar-expand-lg navbar-light d-lg-none navbar-responsive\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Navbar brand -->\r\n");
      out.write("            <a class=\"navbar-brand text-uppercase d-none\" href=\"#\">Navbar</a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Collapse button -->\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent2\"\r\n");
      out.write("                    aria-controls=\"navbarSupportedContent2\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("              <span class=\"navbar-toggler-icon\"><i class='material-icons'>sort</i></span>\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("            <!-- Collapsible content -->\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent2\">\r\n");
      out.write("\r\n");
      out.write("              <!-- Links -->\r\n");
      out.write("              <ul class=\"navbar-nav m-auto justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Features -->\r\n");
      out.write("                <li class=\"nav-item dropdown active\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle text-uppercase\" data-toggle=\"collapse\" data-target=\"#menu1\"\r\n");
      out.write("                     aria-controls=\"menu1\" aria-expanded=\"false\" aria-label=\"Toggle navigation\" href=\"#\">\r\n");
      out.write("                    Home\r\n");
      out.write("                    <span class=\"sr-only\">(current)</span>        </a>\r\n");
      out.write("                  <div class=\"dropdown-menu mega-menu v-2 z-depth-1 special-color py-3 px-3\" id=\"menu1\">\r\n");
      out.write("                    <div class=\"sub-menu mb-xl-0 mb-4\">\r\n");
      out.write("                      <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"index.html\">\r\n");
      out.write("                            Home 2                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"index2.html\">\r\n");
      out.write("                            Home 2                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"index3.html\">\r\n");
      out.write("                            Home 3                 </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"index4.html\">\r\n");
      out.write("                            Home 4                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"index5.html\">\r\n");
      out.write("                            Home 5                  </a>                </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item dropdown mega-dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle text-uppercase\" data-toggle=\"collapse\" data-target=\"#menu3\"\r\n");
      out.write("                     aria-controls=\"menu3\" aria-expanded=\"false\" aria-label=\"Toggle navigation\" href=\"#\">Category</a>\r\n");
      out.write("                  <div class=\"dropdown-menu mega-menu v-2 z-depth-1 special-color py-3 px-3\" id=\"menu3\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-md-12 col-xl-4 sub-menu mb-xl-0 mb-4\">\r\n");
      out.write("                        <h6 class=\"sub-title text-uppercase font-weight-bold white-text\">Variation 1</h6>\r\n");
      out.write("                        <!--Featured image-->\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"filter-toggle.html\">\r\n");
      out.write("                              filter toggle                  </a>                </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"off-canvas-left.html\">\r\n");
      out.write("                              off canvas left                </a>                </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"off-canvas-right.html\">\r\n");
      out.write("                              off canvas right                </a>                </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-6 col-xl-4 sub-menu mb-md-0 mb-4\">\r\n");
      out.write("                        <h6 class=\"sub-title text-uppercase font-weight-bold white-text\">Variation 2</h6>\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"category-5-col.html\">\r\n");
      out.write("                              grid 5 column                 </a>                </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"category-6-col.html\">\r\n");
      out.write("                              grid 6 column                  </a>                </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"category-7-col.html\">\r\n");
      out.write("                              grid 7 column                   </a>                </li>\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <a class=\"menu-item pl-0\" href=\"category-8-col.html\">\r\n");
      out.write("                              grid 8 column                </a>                </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-6 col-xl-4 sub-menu mb-0\">\r\n");
      out.write("\r\n");
      out.write("                        <ul class=\"list-unstyled\">\r\n");
      out.write("                          <li>\r\n");
      out.write("                            <span class=\"menu-banner\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/img/banner/menu-banner.jpg\" alt=\"menu-banner\" width=\"210\" height=\"300\"/></span>                </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle text-uppercase\" data-toggle=\"collapse\" data-target=\"#menu2\"\r\n");
      out.write("                     aria-controls=\"menu2\" aria-expanded=\"false\" aria-label=\"Toggle navigation\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("shop\">\r\n");
      out.write("                    Shop\r\n");
      out.write("                    <span class=\"sr-only\">(current)</span>        </a>\r\n");
      out.write("                  <div class=\"dropdown-menu mega-menu v-2 z-depth-1 special-color py-3 px-3\" id=\"menu2\">\r\n");
      out.write("                    <div class=\"sub-menu mb-xl-0 mb-4\">\r\n");
      out.write("                      <h6 class=\"sub-title text-uppercase font-weight-bold white-text\">Featured</h6>\r\n");
      out.write("                      <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"product-grid.html\">\r\n");
      out.write("                            product grid                </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"product-sticky-right.html\">\r\n");
      out.write("                            sticky right                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"product-extended-layout.html\">\r\n");
      out.write("                            Extended layout                 </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"product-details.html\">\r\n");
      out.write("                            Default layout                </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"product-compact.html\">\r\n");
      out.write("                            compact layout           </a>                </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- Technology -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle text-uppercase\"  data-toggle=\"collapse\" data-target=\"#menu4\"\r\n");
      out.write("                     aria-controls=\"menu4\" aria-expanded=\"false\" aria-label=\"Toggle navigation\" href=\"#\">Blog</a>\r\n");
      out.write("                  <div class=\"dropdown-menu mega-menu v-2 z-depth-1 special-color py-3 px-3\" id=\"menu4\">\r\n");
      out.write("                    <div class=\"sub-menu\">\r\n");
      out.write("                      <h6 class=\"sub-title text-uppercase font-weight-bold white-text d-none\">Featured</h6>\r\n");
      out.write("                      <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"blog-2-column.html\">\r\n");
      out.write("                            blog 2 column                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"blog-3-column.html\">\r\n");
      out.write("                            blog 3 column                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"blog-2-column-masonary.html\">\r\n");
      out.write("                            blog masonary                 </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"blog-list.html\">\r\n");
      out.write("                            blog list                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"blog-details.html\">\r\n");
      out.write("                            blog details                  </a>                </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link text-uppercase\" href=\"contact-us.html\">contact us</a>      </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                  <a class=\"nav-link dropdown-toggle text-uppercase\"  data-toggle=\"collapse\" data-target=\"#menu5\"\r\n");
      out.write("                     aria-controls=\"menu5\" aria-expanded=\"false\" aria-label=\"Toggle navigation\" href=\"#\">Pages</a>\r\n");
      out.write("                  <div class=\"dropdown-menu mega-menu v-2 z-depth-1 special-color py-3 px-3\" id=\"menu5\">\r\n");
      out.write("                    <div class=\"sub-menu\">\r\n");
      out.write("                      <h6 class=\"sub-title text-uppercase font-weight-bold white-text d-none\">Featured</h6>\r\n");
      out.write("                      <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"about-us.html\">\r\n");
      out.write("                            About us                 </a>				 </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"accordions.html\">\r\n");
      out.write("                            Accordions                  </a>                </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                          <a class=\"menu-item pl-0\" href=\"buttons.html\">\r\n");
      out.write("                            Buttons              </a>                </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <!-- Links -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Collapsible content -->\r\n");
      out.write("\r\n");
      out.write("          </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
