/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-02 11:50:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class base_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/TUF/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692297127045L));
    _jspx_dependants.put("jar:file:/C:/Users/TUF/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Fashion Template for Bootstrap</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"Demo powered by Templatetrip\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/favicon.ico\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:400,500,700,900\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/bootstrap/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/owl-carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/lightbox.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.payhere.lk/lib/payhere.js\"></script>\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"index layout1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fblock_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"alert text-center cookiealert\" role=\"alert\">\r\n");
      out.write("    <b>Do you like cookies?</b> We use cookies to ensure you get the best experience on our website. <a href=\"https://demo.templatetrip.com/Html/HTML001_victoria/\" rel=\"noreferrer\">learn more</a>\r\n");
      out.write("\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary btn-sm acceptcookies\" aria-label=\"Close\">\r\n");
      out.write("        I agree\r\n");
      out.write("    </button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Register modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"modalRegisterForm\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header text-center\">\r\n");
      out.write("                <h4 class=\"modal-title w-100 font-weight-medium text-left\">Sign up</h4>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body mx-3\">\r\n");
      out.write("                <div class=\"md-form mb-4\">\r\n");
      out.write("                    <input type=\"text\" id=\"RegisterForm-name\" class=\"form-control validate\" placeholder=\"Your name\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"md-form mb-4\">\r\n");
      out.write("                    <input type=\"email\" id=\"RegisterForm-email\" class=\"form-control validate\" placeholder=\"Your email\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"md-form mb-4\">\r\n");
      out.write("                    <input type=\"password\" id=\"RegisterForm-pass\" class=\"form-control validate\" placeholder=\"Your password\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"checkbox-link d-flex justify-content-between\">\r\n");
      out.write("                    <div class=\"left-col\">\r\n");
      out.write("                        <input id=\"remember-me\" type=\"checkbox\"><label for=\"remember_me\">Remember Me</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"right-col\"><a href=\"#\">Forget Password?</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"modal-footer d-flex justify-content-center\">\r\n");
      out.write("                <button class=\"btn btn-primary sign-up\">Sign up</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Login modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"modalLoginForm\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header text-center\">\r\n");
      out.write("                <h4 class=\"modal-title w-100 font-weight-medium text-left\">Sign in</h4>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body mx-3\">\r\n");
      out.write("                <div class=\"md-form mb-4\">\r\n");
      out.write("                    <input type=\"text\" id=\"LoginForm-email\" class=\"form-control validate\" placeholder=\"Your email\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"md-form mb-4\">\r\n");
      out.write("                    <input type=\"password\" id=\"LoginForm-pass\" class=\"form-control validate\" placeholder=\"Your password\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"checkbox-link d-flex justify-content-between\">\r\n");
      out.write("                    <div class=\"left-col\">\r\n");
      out.write("                        <input type=\"checkbox\" id=\"remember_me\"><label for=\"remember_me\">Remember Me</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"right-col\"><a href=\"#\">Forget Password?</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"modal-footer d-flex justify-content-center\">\r\n");
      out.write("                <button class=\"btn btn-primary sign-in\">Sign in</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- product_view modal -->\r\n");
      out.write("<div class=\"modal fade product_view\" id=\"product_view\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h4 class=\"modal-title w-100w-100w-100 font-weight-bold d-none\">Quick view</h4>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 left-columm\">\r\n");
      out.write("                        <div class=\"product-large-image tab-content\">\r\n");
      out.write("                            <div class=\"tab-pane active\" id=\"product-1\" role=\"tabpanel\" aria-labelledby=\"product-tab-1\">\r\n");
      out.write("                                <div class=\"single-img img-full\">\r\n");
      out.write("                                    <a href=\"img/productDTO/01.jpg\"><img src=\"img/productDTO/01.jpg\" class=\"img-fluid\" alt=\"\" width=\"368\" height=\"478\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tab-pane\" id=\"product-2\" role=\"tabpanel\" aria-labelledby=\"product-tab-2\">\r\n");
      out.write("                                <div class=\"single-img\">\r\n");
      out.write("                                    <a href=\"img/productDTO/02.jpg\"><img src=\"img/productDTO/02.jpg\" class=\"img-fluid\" alt=\"\" width=\"368\" height=\"478\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tab-pane\" id=\"product-3\" role=\"tabpanel\" aria-labelledby=\"product-tab-3\">\r\n");
      out.write("                                <div class=\"single-img\">\r\n");
      out.write("                                    <a href=\"img/productDTO/03.jpg\"><img src=\"img/productDTO/03.jpg\" class=\"img-fluid\" alt=\"\" width=\"368\" height=\"478\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tab-pane\" id=\"product-4\" role=\"tabpanel\" aria-labelledby=\"product-tab-4\">\r\n");
      out.write("                                <div class=\"single-img\">\r\n");
      out.write("                                    <a href=\"img/productDTO/04.jpg\"><img src=\"img/productDTO/04.jpg\" class=\"img-fluid\" alt=\"\" width=\"368\" height=\"478\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tab-pane\" id=\"product-5\" role=\"tabpanel\" aria-labelledby=\"product-tab-5\">\r\n");
      out.write("                                <div class=\"single-img\">\r\n");
      out.write("                                    <a href=\"img/productDTO/05.jpg\"><img src=\"img/productDTO/05.jpg\" class=\"img-fluid\" alt=\"\" width=\"368\" height=\"478\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"small-image-list float-left w-100\">\r\n");
      out.write("                            <div class=\"nav-add small-image-slider-single-product-tabstyle-3 owl-carousel\" role=\"tablist\">\r\n");
      out.write("                                <div class=\"single-small-image img-full\">\r\n");
      out.write("                                    <a data-toggle=\"tab\" id=\"product-tab-1\" href=\"#product-1\" class=\"img active\"><img src=\"img/productDTO/01.jpg\" class=\"img-fluid\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-small-image img-full\">\r\n");
      out.write("                                    <a data-toggle=\"tab\" id=\"product-tab-2\" href=\"#product-2\" class=\"img\"><img src=\"img/productDTO/02.jpg\" class=\"img-fluid\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-small-image img-full\">\r\n");
      out.write("                                    <a data-toggle=\"tab\" id=\"product-tab-3\" href=\"#product-3\" class=\"img\"><img src=\"img/productDTO/03.jpg\" class=\"img-fluid\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-small-image img-full\">\r\n");
      out.write("                                    <a data-toggle=\"tab\" id=\"product-tab-4\" href=\"#product-4\" class=\"img\"><img src=\"img/productDTO/04.jpg\" class=\"img-fluid\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-small-image img-full\">\r\n");
      out.write("                                    <a data-toggle=\"tab\" id=\"product-tab-5\" href=\"#product-5\" class=\"img\"><img src=\"img/productDTO/05.jpg\" class=\"img-fluid\" alt=\"\"></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 product_content\">\r\n");
      out.write("                        <h4 class=\"product-title text-capitalize\">Printed Polo Collar T-shirt</h4>\r\n");
      out.write("                        <div class=\"rating\">\r\n");
      out.write("                            <div class=\"product-ratings d-inline-block align-middle\">\r\n");
      out.write("                                <span class=\"fa fa-stack\"><i class=\"material-icons\">star</i></span>\r\n");
      out.write("                                <span class=\"fa fa-stack\"><i class=\"material-icons\">star</i></span>\r\n");
      out.write("                                <span class=\"fa fa-stack\"><i class=\"material-icons\">star</i></span>\r\n");
      out.write("                                <span class=\"fa fa-stack\"><i class=\"material-icons off\">star</i></span>\r\n");
      out.write("                                <span class=\"fa fa-stack\"><i class=\"material-icons off\">star</i></span>			</div>							</div>\r\n");
      out.write("                        <span class=\"description float-left w-100\">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</span>\r\n");
      out.write("                        <h3 class=\"price float-left w-100\"><span class=\"regular-price align-middle\">$75.00</span><span class=\"old-price align-middle\">$60.00</span></h3>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"product-variants float-left w-100\">\r\n");
      out.write("                            <div class=\"col-md-4 col-sm-6 col-xs-12 size-options d-flex align-items-center\">\r\n");
      out.write("                                <h5>Size:</h5>\r\n");
      out.write("\r\n");
      out.write("                                <select class=\"form-control\" name=\"select\">\r\n");
      out.write("                                    <option value=\"\" selected=\"\">Size</option>\r\n");
      out.write("                                    <option value=\"black\">Medium</option>\r\n");
      out.write("                                    <option value=\"white\">Large</option>\r\n");
      out.write("                                    <option value=\"gold\">Small</option>\r\n");
      out.write("                                    <option value=\"rose gold\">Extra large</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"color-option d-flex align-items-center\">\r\n");
      out.write("                                <h5>color :</h5>\r\n");
      out.write("                                <ul class=\"color-categories\">\r\n");
      out.write("                                    <li class=\"active\">\r\n");
      out.write("                                        <a class=\"tt-pink\" href=\"#\" title=\"Pink\"></a>                                            </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a class=\"tt-blue\" href=\"#\" title=\"Blue\"></a>                                            </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a class=\"tt-yellow\" href=\"#\" title=\"Yellow\"></a>                                            </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"btn-cart d-flex align-items-center float-left w-100\">\r\n");
      out.write("                            <h5>qty:</h5>\r\n");
      out.write("                            <input value=\"1\" type=\"number\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary\"><i class=\"material-icons\">shopping_cart</i> Add To Cart</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- cart-pop modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"cart-pop\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header alert-success\">\r\n");
      out.write("                <h4 class=\"modal-title w-100w-100w-100\">Product successfully added to your shopping cart</h4>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 divide-right\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-5 col-sm-4 col-xs-12 product-img float-left\">\r\n");
      out.write("                                <img src=\"img/productDTO/01.jpg\" class=\"img-responsive\" alt=\"01\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-7 col-sm-8 col-xs-12 product-desc float-left\">\r\n");
      out.write("                                <h4 class=\"product-title text-capitalize\">Burgundy Small Dress</h4>\r\n");
      out.write("                                <div class=\"rating\">\r\n");
      out.write("                                    <div class=\"product-ratings d-inline-block align-middle\">\r\n");
      out.write("                                        <span class=\"fa fa-stack\"><i class=\"material-icons\">star</i></span>\r\n");
      out.write("                                        <span class=\"fa fa-stack\"><i class=\"material-icons\">star</i></span>\r\n");
      out.write("                                        <span class=\"fa fa-stack\"><i class=\"material-icons\">star</i></span>\r\n");
      out.write("                                        <span class=\"fa fa-stack\"><i class=\"material-icons off\">star</i></span>\r\n");
      out.write("                                        <span class=\"fa fa-stack\"><i class=\"material-icons off\">star</i></span></div></div>\r\n");
      out.write("                                <h3 class=\"price float-left w-100\"><span class=\"regular-price align-middle\">$75.00</span><span class=\"old-price align-middle\">$60.00</span></h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 divide-left\">\r\n");
      out.write("                        <p class=\"cart-productDTO-count\">There are 2 items in your cart.</p>\r\n");
      out.write("                        <p class=\"total-productDTO float-left w-100\">\r\n");
      out.write("                            <strong>Total productDTO:</strong> $150.00\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p class=\"shipping float-left w-100\">\r\n");
      out.write("                            <strong>Total shipping:</strong> free\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p class=\"total-price float-left w-100\">\r\n");
      out.write("                            <strong>Total:</strong> $150.00(tax incl.)\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <div class=\"cart-content-btn float-left w-100\">\r\n");
      out.write("                            <form action=\"#\">\r\n");
      out.write("                                <input class=\"btn pull-right mt_10 btn-primary\" value=\"Continue shopping\" type=\"submit\">\r\n");
      out.write("                            </form>\r\n");
      out.write("                            <form action=\"checkout_page.html\">\r\n");
      out.write("                                <input class=\"btn pull-right mt_10 btn-secondary\" value=\"Proceed to checkout\" type=\"submit\">\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"compare-wrapper float-left w-100\">\r\n");
      out.write("    <div class=\"compare-inner d-flex align-items-center p-20\">\r\n");
      out.write("		<span class=\"close\"><i class='material-icons'>\r\n");
      out.write("  close\r\n");
      out.write("</i></span>\r\n");
      out.write("        <div class=\"col-xs-12 col-sm-2 col-md-3 float-left d-flex align-items-center flex-column compare-left\">\r\n");
      out.write("            <h2>compare productDTO</h2>\r\n");
      out.write("            <div class=\"compare-btn\">show all</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xs-12 col-sm-10 col-md-9 d-flex float-left align-items-center compare-right\">\r\n");
      out.write("            <div class=\"compare-close-btn\"></div>\r\n");
      out.write("            <div class=\"compare-productDTO d-flex col-sm-7 col-lg-5\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"single-item col-sm-4 col-xs-4\">\r\n");
      out.write("                        <div class=\"remove\"></div>\r\n");
      out.write("                        <div class=\"image\"><img src=\"img/productDTO/01.jpg\" class=\"img-fluid\" alt=\"\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"single-item col-sm-4 col-xs-4\">\r\n");
      out.write("                        <div class=\"remove\"></div>\r\n");
      out.write("                        <div class=\"image\"><img src=\"img/productDTO/02.jpg\" class=\"img-fluid\" alt=\"\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"single-item col-sm-4 col-xs-4\">\r\n");
      out.write("                        <div class=\"remove\"></div>\r\n");
      out.write("                        <div class=\"image\"><img src=\"img/productDTO/03.jpg\" class=\"img-fluid\" alt=\"\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"buttons col-sm-5 col-lg-2\">\r\n");
      out.write("                <a href=\"compare.html\" class=\"compare-btn btn btn-secondary float-left w-100 mb-15\">compare</a>\r\n");
      out.write("                <div class=\"clear-btn btn btn-primary float-left w-100\">clear</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript\r\n");
      out.write("================================================== -->\r\n");
      out.write("<!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/custom.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/parallax.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/lightbox-2.6.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/ResizeSensor.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/theia-sticky-sidebar.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/inview.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/cookiealert.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/masonry.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/jquery.zoom.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/jquery.lazy.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/payment.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.payhere.lk/lib/payhere.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    let e = document.getElementsByClassName('sign-up').item(0).addEventListener('click',()=>{\r\n");
      out.write("        let name = document.getElementById('RegisterForm-name').value;\r\n");
      out.write("        let email = document.getElementById('RegisterForm-email').value;\r\n");
      out.write("        let password = document.getElementById('RegisterForm-pass').value;\r\n");
      out.write("\r\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("register',{\r\n");
      out.write("            method:'post',\r\n");
      out.write("            headers:{\r\n");
      out.write("                'Content-Type':'application/json'\r\n");
      out.write("            },\r\n");
      out.write("            body:JSON.stringify({\r\n");
      out.write("                name:name,\r\n");
      out.write("                email:email,\r\n");
      out.write("                password:password\r\n");
      out.write("            })\r\n");
      out.write("        }).then(response => response.text()).then(text=>console.log(text))\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    let login = document.getElementsByClassName('sign-in').item(0).addEventListener('click',()=>{\r\n");
      out.write("        const email = document.getElementById('LoginForm-email').value;\r\n");
      out.write("        const password = document.getElementById('LoginForm-pass').value;\r\n");
      out.write("\r\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("login',{\r\n");
      out.write("            method:'post',\r\n");
      out.write("            headers:{\r\n");
      out.write("                'Content-Type':'application/json'\r\n");
      out.write("            },\r\n");
      out.write("            body:JSON.stringify({\r\n");
      out.write("                email:email,\r\n");
      out.write("                password:password\r\n");
      out.write("            })\r\n");
      out.write("        }).then(response => response.text())\r\n");
      out.write("            .then(text=>{\r\n");
      out.write("                if(text === \"USER\"){\r\n");
      out.write("                    alert(\"Welcome\")\r\n");
      out.write("                }else if(text === \"ADMIN\"){\r\n");
      out.write("                    window.location = 'admin-panel';\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fblock_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f0 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f0);
    try {
      _jspx_th_layout_005fblock_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout/base.jsp(47,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f0.setName("contents");
      _jspx_th_layout_005fblock_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fblock_005f0, null));
      _jspx_th_layout_005fblock_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
